---
### Required Vars
## inventory_name
## organization
## group_name
## awx_host
## awx_username
## awx_password

- name: Ensure inventory exists in AWX
  awx.awx.inventory:
    name: "{{ inventory_name }}"
    organization: "{{ organization }}"
    controller_host: "{{ awx_host }}"
    controller_username: "{{ awx_username }}"
    controller_password: "{{ awx_password }}"
    validate_certs: false
    state: present
  register: inventory
  # delegate_to: localhost

- name: Ensure group exists in the inventory
  awx.awx.group:
    name: "{{ group_name }}"
    inventory: "{{ inventory.id }}"
    tower_host: "{{ awx_host }}"
    tower_username: "{{ awx_username }}"
    tower_password: "{{ awx_password }}"
    state: present
  register: group
  delegate_to: localhost


- name: loop over port_mappings
  ansible.builtin.debug:
    var: item
  loop: "{{ port_mappings.port_mappings | dict2items }}"
  delegate_to: localhost


- name: Add hosts to the AWX group
  awx.awx.host:
    name: "{{ item.key }}"
    inventory: "{{ inventory.id }}"
    variables:
      ansible_host: "{{ shared_ip }}"
      ansible_port: "{{ item.value }}"
    tower_host: "{{ awx_host }}"
    tower_username: "{{ awx_username }}"
    tower_password: "{{ awx_password }}"
    state: present
  loop: "{{ port_mappings.port_mappings | dict2items }}"
  delegate_to: localhost
